### ISSUE TITLE
There is a problem with the download icon

### ISSUE THREAD

**Issue by windorz9** [CocoaDebug/GoogleTranslate#3]
仔细寻觅一番就找到了这个应用, 挺好用的, 关于点击下面的两个 android 和 iOS 客户端的按钮, 点 android 那个还没有问题, 手贱多点了几次 iOS 下载那个按钮就直接跳到了网页版的 app store 了, 然后就回不去了, 好像. 非要退出再进入才行. 😯

**Comment by CocoaDebug** [comment]
没关系，重新打开就好了。

**Comment by windorz9** [comment]
emmm 这么皮吗 😁

**Comment by CocoaDebug** [comment]
🚀New Mac App successfully published.
Please update to last version. Thanks!
