### ISSUE TITLE
How can I start the app?

### ISSUE THREAD

**Issue by UnixCro** [CocoaDebug/GoogleTranslate#4]
Where can I download it as an app?

**Comment by CocoaDebug** [comment]
[Download Link](https://raw.githubusercontent.com/CocoaDebug/GoogleTranslate/master/Google%20Translate.app.zip)

**Comment by UnixCro** [comment]
The app is honestly cool. Nice job and thanks for the quick reply.
The app worked immediately without any problems and I will use it more often now. It saves me a lot of time and energy that I wasted all the time searching from google translate in the web browser.

Thank you very much for the great project!
I follow you and hope for more great projects
